curl -X POST 'http://localhost:3000/upload' \
  --header 'User-Agent: cli' \
  --header 'Accept: */*' \
  --header 'Authorization: test' \
  --header 'Content-Type: multipart/form-data' \
  --header 'Expect: ' \
  --form 'accessKeyId=${ACCESS_KEY_ID}' \
  --form 'secretAccessKey=${SECRET_ACCESS_KEY}' \
  --form 'endpoint=${ENDPOINT}' \
  --form 'bucket=${BUCKET}' \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/rabbitholes-app-7.0.1-arm64.dmg \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/rabbitholes-app-7.0.1-setup.exe \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/rabbitholes-app-7.0.1-setup.exe.blockmap \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/rabbitholes-app-7.0.1-x64.dmg \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/rabbitholes-app-7.0.1.AppImage \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/RabbitHolesAI-7.0.1-amd64.deb \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/RabbitHolesAI-7.0.1-arm64-mac.zip \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/RabbitHolesAI-7.0.1-arm64-mac.zip.blockmap \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/RabbitHolesAI-7.0.1-mac.zip \
  --form file=@/Users/praneethpike/Work/fluidchat/artifacts/v7.0.1/RabbitHolesAI-7.0.1-mac.zip.blockmap